### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by Shadowveil-WotLK**
Fixes issue: #7

### CODE REVIEW

**Comment by Shadowveil-WotLK** [comment]
@Helias would be nice if u could approve this PR =)

Thx in advance already! =D

**Comment by Helias** [comment]
sure, when I'll merge it when the build pass

**Comment by Helias** [comment]
It failed, please fix the build

**Comment by Helias** [comment]
try to align your PR with the updated master branch where I updated the pipeline build settings

**Comment by Shadowveil-WotLK** [comment]
aha i see.
probably because i am using actually a revision from mid of april from acore ^^
will grab the actual one when home and update it then =)

**Comment by Shadowveil-WotLK** [comment]
good... grabbed now latest acore revision, integrated the pipeline change too on my pr and performed the change of the query as well after i tested it on my testserver instance. '%s' got changed now to '{}'... that way it had on actual revision no error on build =D

**Comment by Helias** [comment]
```
[ 20%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/CreatureAIRegistry.cpp.o
/home/runner/work/mod-chat-login/mod-chat-login/modules/mod-chat-login/src/LoginChat.cpp:18:40: fatal error: 'GetStringDefault' is deprecated: Use GetOption<std::string> instead [-Wdeprecated-declarations]
        std::string channelName = sConfigMgr->GetStringDefault("LoginChat.name", "world");
                                              ^
/home/runner/work/mod-chat-login/mod-chat-login/src/common/Configuration/Config.h:54:7: note: 'GetStringDefault' has been explicitly marked deprecated here
    [[deprecated("Use GetOption<std::string> instead")]]
      ^
1 error generated.
make[2]: *** [modules/CMakeFiles/modules.dir/build.make:90: modules/CMakeFiles/modules.dir/mod-chat-login/src/LoginChat.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1217: modules/CMakeFiles/modules.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by Shadowveil-WotLK** [comment]
sorry for my late reply, was bit in stress and then not home some days.

hmmmm... that is pretty strange actually since was able to build it without any problems at latest msvc on win server 2019 in debug mode (see screenshot). checking it now again with relwithdebinfo build mode.

EDIT: 
and kk checked also your error message now more proper which u posted.... i see what the problem is ^^

image

**Comment by Shadowveil-WotLK** [comment]
changed the deprecated GetStringDefault

**Comment by Helias** [comment]
Perfect!

**Pull request merged**
